#cloud-config

coreos:
  update:
    group: GROUP
    reboot-strategy: off
  etcd:
    name: etcd
    addr: $private_ipv4:4001
    bind-addr: 0.0.0.0
    peer-addr: $private_ipv4:7001
    cluster-active-size: 1
    etcd-http-read-timeout: 86400
    snapshot: true
  fleet:
    etcd_servers: http://127.0.0.1:4001
    metadata: role=control
  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.244.0.0/16" }'
      command: start
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
write_files:
 - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
   content: |
     [Service]
     Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'
